creation_rules:
  - age:
    - age17d0gwhrtfchc0qgfxfu2xrgjnag2f3ruuhc84qkpsxc2lq6ppsaqyfqhgs
    - age1mw0v48f423zcnu58r8d2d9qatp9xnzj4ykvu2a8mfajr2umylepscsnnpw
    - age1fqyczg828z9wq2rwznjkvvn5yl705gsdam4ezthp9eyce97kzu0q267k4k
