version: '3'
tasks:
  install:
    desc: Install dev dependencies
    cmds:
      - go install github.com/google/yamlfmt/cmd/yamlfmt@latest
  lint-check:
    desc: Lint (check only)
    cmds:
      - tofu fmt -check -diff
      - yamlfmt -lint .github/actions/*.yml ansible/**/*.yml.j2 ansible/**/*.yml *.yml *.yaml
  lint-fix:
    desc: Lint (fix)
    cmds:
      - tofu fmt
      - yamlfmt .github/actions/*.yml ansible/**/*.yml.j2 ansible/**/*.yml *.yml *.yaml
