services:
  beszel_agent:
    env_file: .env.beszel_agent
    image: henrygd/beszel-agent:0.18.7-alpine
    labels:
      io.portainer.accesscontrol.teams: operators
      traefik.enable: "false"
    network_mode: host
    privileged: true
    cap_add:
      - SYS_RAWIO
    restart: unless-stopped
    volumes:
      - /dev/sata1:/dev/sata1
      - /dev/sata2:/dev/sata2
      - /dev/sata3:/dev/sata3
      - /dev/sata4:/dev/sata4
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/extra-filesystems/root__md0:ro
      - /volume1:/extra-filesystems/volume1__volume1:ro
  diun:
    env_file: .env.diun
    hostname: s920p
    image: crazymax/diun:4.31.0
    labels:
      io.portainer.accesscontrol.teams: operators
      traefik.enable: "false"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /volume2/var/diun
        target: /data
  dozzle_agent:
    command:
      - agent
    env_file: .env.dozzle_agent
    hostname: s920p
    image: amir20/dozzle:v10.5.1
    labels:
      io.portainer.accesscontrol.teams: operators
      traefik.enable: "false"
    networks:
      netsvc: {}
    ports:
      - target: 7007
        published: "7007"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
  portainer_agent:
    env_file: .env.portainer_agent
    image: portainer/agent:2.40.0-alpine
    labels:
      io.portainer.accesscontrol.teams: operators
      traefik.enable: "false"
    restart: unless-stopped
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        read_only: true
      - type: bind
        source: /volume2/var/portainer
        target: /data
networks:
  netsvc:
    name: netsvc
    external: true
