ungrouped:
  hosts:
    internal_net:
      ansible_host: replo.de
    s920p:
      ansible_host: 10.42.20.78

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    secrets: "{{ lookup('community.sops.sops', '../config/secrets.enc.json') | ansible.builtin.from_json }}"

remote:
  hosts:
    internal_net:

local:
  hosts:
    s920p:
