ungrouped:
  hosts:
    internal_net:
      ansible_host: replo.de
    s920p:
      ansible_host: 10.42.20.78
      ansible_port: 5022
      ansible_user: "{{ secrets.dsm.username }}"
      ansible_password: "{{ secrets.dsm.password }}"
      ansible_ssh_private_key_file: ~/.ssh/{{ lookup('ansible.builtin.env', 'TF_VAR_ssh_identity', default='ssh_ed25519') }}
      ansible_become: true
      ansible_become_password: "{{ secrets.dsm.password }}"
      ansible_scp_extra_args: -O

all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
    secrets: "{{ lookup('community.sops.sops', '../config/secrets.enc.json') | ansible.builtin.from_json }}"

remote:
  hosts:
    internal_net:

local:
  hosts:
    s920p:
