---
- hosts: s920p
  remote_user: docker

  tasks:
  - ansible.builtin.wait_for_connection:

  - ansible.builtin.include_role:
      name: docker_project
    vars:
      project_name: "{{ item }}"
    loop:
      - kan
      - rss
      - mmclients
