---
- hosts: remote
  remote_user: root
  
  tasks:
  - name: Disallow SSH password authentication
    lineinfile:
      dest=/etc/ssh/sshd_config
      regexp="^PasswordAuthentication"
      line="PasswordAuthentication no"
      state=present
      validate: sshd -t -f %s
    notify:
      - restart sshd
