- name: Load {{ project_name }} vars
  ansible.builtin.include_vars: "{{ lookup('ansible.builtin.first_found', params) }}"
  vars:
    params:
    - "../vars/{{ project_name }}.yml"
    - ../vars/default.yml

- ansible.builtin.file:
    path: /volume2/var/{{ var_dir | trim('/') }}
    state: directory
    owner: 100
    group: 101
    mode: '0755'
  loop: "{{ var_dirs | default([]) }}"
  loop_control:
    loop_var: var_dir

- name: Copy {{ project_name }}/var files
  ansible.builtin.template:
    src: "{{ filetree_item.src }}"
    dest: /volume2/var/{{ filetree_item.path }}
    owner: 100
    group: 101
    mode: '0640'
  with_community.general.filetree: ../files/{{ project_name }}/var
  loop_control:
    label: "{{ filetree_item.path }}"
    loop_var: filetree_item
  when: filetree_item.state == 'file'

- name: Copy {{ project_name }}/var templates
  ansible.builtin.template:
    src: "{{ filetree_item.src }}"
    dest: /volume2/var/{{ (filetree_item.path | splitext)[0] }}
    owner: 100
    group: 101
    mode: '0640'
  with_community.general.filetree: ../templates/{{ project_name }}/var
  loop_control:
    label: "{{ filetree_item.path }}"
    loop_var: filetree_item
  when: filetree_item.state == 'file'

- name: Assert {{ project_name }} project path
  ansible.builtin.file:
    path: /volume2/docker/{{ project_name }}
    state: directory
    owner: 400000
    group: 400000
    mode: '0755'

- name: Copy {{ project_name }} compose.yml
  ansible.builtin.copy:
    src: "files/{{ project_name }}/{{ fileglob_item | basename }}"
    dest: /volume2/docker/{{ project_name }}
    owner: 400000
    group: 400000
    mode: '0644'
  loop_control:
    loop_var: fileglob_item
  with_fileglob:
    - "files/{{ project_name }}/*.yml"

- name: Copy {{ project_name }} .env files
  ansible.builtin.copy:
    src: "{{ fileglob_item }}"
    dest: /volume2/docker/{{ project_name }}/{{ fileglob_item | basename }}
    owner: 400000
    group: 400000
    mode: '0644'
  loop_control:
    loop_var: fileglob_item
  with_fileglob:
    - "files/{{ project_name }}/env/.*"

- name: Generate {{ project_name }} .env files
  ansible.builtin.template:
    src: "{{ fileglob_item }}"
    dest: /volume2/docker/{{ project_name }}/{{ (fileglob_item | basename | splitext)[0] }}
    owner: 400000
    group: 400000
    mode: '0644'
  loop_control:
    loop_var: fileglob_item
  with_fileglob:
    - "templates/{{ project_name }}/env/.*.j2"

- name: Stat .env.compose
  ansible.builtin.stat:
    path: /volume2/docker/{{ project_name }}/.env.compose
  register: stat

- name: Bring up {{ project_name }}
  community.docker.docker_compose_v2:
    docker_cli: /usr/local/bin/docker
    project_src: /volume2/docker/{{ project_name }}
    env_files: .env.compose
    state: present
  when: stat.stat.exists is true

- name: Bring up {{ project_name }}
  community.docker.docker_compose_v2:
    docker_cli: /usr/local/bin/docker
    project_src: /volume2/docker/{{ project_name }}
    state: present
  when: stat.stat.exists is false
