- ansible.builtin.wait_for_connection:

- ansible.builtin.include_tasks: docker_project.yml
  vars:
    project_name: "{{ item }}"
  loop:
    - monsvc
    - mmclients
    - mmproviders
    - kan
    - rss
    - bak
    - pho
    - keep
    - llm
    - netsvc # supposed to come first to create some networks
