on:
  pull_request:

name: ansible

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          age-key: ${{ secrets.AGE_KEY }}
          ssk-key: ${{ secrets.SSH_KEY }}
          tailscale-oauth-id: ${{ secrets.TAILSCALE_OAUTH_ID }}
          tailscale-oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          dsm-host: ${{ vars.DSM_HOST }}
      - run: |
          sudo apt update
          sudo apt install -y ansible
      - run: ansible-playbook -i hosts.yml remote.yml
        working-directory: ./ansible