on:
  workflow_dispatch:
  push:
    paths:
      - 'ansible/**'
      - 'config/**'
    branches:
      - main

name: ansible

jobs:
  playbook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/init
        with:
          age-key: ${{ secrets.AGE_KEY }}
          ssh-key: ${{ secrets.SSH_KEY }}
          tailscale-oauth-id: ${{ secrets.TAILSCALE_OAUTH_ID }}
          tailscale-oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          dsm-host: ${{ vars.DSM_HOST }}
      - uses: astral-sh/setup-uv@v7
      - run: uv tool install ansible-core --with ansible
      - run: ansible-playbook -i hosts.yml remote.yml
