on:
  workflow_dispatch:
  push:
    branches:
      - main

name: apply

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  apply:
    defaults:
      run:
        working-directory: ./terraform
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      AWS_ENDPOINT_URL_S3: ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET }}
      TF_VAR_tf_passphrase: ${{ secrets.TF_PASSPHRASE }}
      TF_VAR_ssh_identity: id_ed25519_github
    steps:
      - uses: ./.github/actions/init
        with:
          age-key: ${{ secrets.AGE_KEY }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-identity: id_ed25519_github
          tailscale-oauth-id: ${{ secrets.TAILSCALE_OAUTH_ID }}
          tailscale-oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          dsm-host: ${{ vars.DSM_HOST }}
      - uses: opentofu/setup-opentofu@v2
      - run: tofu init
      - run: tofu validate -no-color
      - run: tofu plan -out=out.tfplan
      - run: tofu apply -auto-approve out.tfplan
