on:
  workflow_dispatch:

name: destroy

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      AWS_ENDPOINT_URL_S3: ${{ vars.CLOUDFLARE_R2_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_R2_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_R2_SECRET }}
      TF_VAR_tf_passphrase: ${{ secrets.TF_PASSPHRASE }}
      TF_VAR_ssh_identity: id_ed25519_github
      TF_VAR_hcloud_newt_id: ${{ vars.HCLOUD_NEWT_ID }}
      TF_VAR_hcloud_newt_secret: ${{ secrets.HCLOUD_NEWT_SECRET }}
      TF_VAR_s920p_newt_id: ${{ vars.S920P_NEWT_ID }}
      TF_VAR_s920p_newt_secret: ${{ secrets.S920P_NEWT_SECRET }}
      TF_VAR_cloudflare_dns_api_token: ${{ secrets.CLOUDFLARE_DNS_API_TOKEN }}
      TF_VAR_wg_easy_init_password: ${{ secrets.WG_EASY_INIT_PASSWORD }}
    steps:
      - run: echo "TF_LOG=DEBUG" >> $GITHUB_ENV
        if: runner.debug == '1'
      - uses: actions/checkout@v6
      - run: |
          mkdir -p $XDG_CONFIG_HOME/sops/age/ ~/.ssh/
          echo "$AGE_KEY" > $XDG_CONFIG_HOME/sops/age/keys.txt
          echo "$SSH_KEY" > ~/.ssh/id_ed25519_github
          chmod 600 ~/.ssh/id_ed25519_github
        env:
          AGE_KEY: ${{ secrets.AGE_KEY }}
          SSH_KEY: ${{secrets.SSH_KEY}}
      - uses: tailscale/github-action@v4
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_SECRET }}
          tags: tag:github
          ping: ${{ vars.DSM_HOST }}
      - uses: opentofu/setup-opentofu@v2
      - run: tofu init
      - run: tofu validate -no-color
      - run: tofu plan -destroy -out=out.tfplan
      - run: tofu apply -auto-approve out.tfplan
